# RESEARCH QUESTION
### "Which degree fields offer fresh graduates the best combination of salary and job security in Singapore?"
- Which degree fields have the highest starting salaries and employment rates?
- How resilient are different fields during economic downturns (e.g., 2020 COVID)?

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df1 = pd.read_csv('CA2 Datasets\CA2 Datasets\(1) graduate employment survey modified.csv')
df2 = pd.read_csv('CA2 Datasets\CA2 Datasets\(2) graduate employment survey modified .csv')

In [3]:
df3 = pd.read_csv('CA2 Datasets/CA2 Datasets/employed_15_sex_edu_age_yr.csv')
df4 = pd.read_excel('CA2 Datasets/CA2 Datasets/LFR2023_SectionD.xlsx', sheet_name='D1', skiprows=6)

In [4]:
display(df1.head())
print(df1.info())

,year,university,school,degree,Key
0,2013,Nanyang Technological University,College of Business (Nanyang Business School),Accountancy and Business,1
1,2013,Nanyang Technological University,College of Business (Nanyang Business School),Accountancy (3-yr direct Honours Programme),2
2,2013,Nanyang Technological University,College of Business (Nanyang Business School),Business (3-yr direct Honours Programme),3
3,2013,Nanyang Technological University,College of Business (Nanyang Business School),Business and Computing,4
4,2013,Nanyang Technological University,College of Engineering,Aerospace Engineering,5

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5135 entries, 0 to 5134
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        5135 non-null   object
 1   university  5135 non-null   object
 2   school      5135 non-null   object
 3   degree      5135 non-null   object
 4   Key         5135 non-null   int64
dtypes: int64(1), object(4)
memory usage: 200.7+ KB
None

In [5]:
display(df2.head())
print(df2.info())

,employment_rate_overall,employment_rate_ft_perm,basic_monthly_mean,basic_monthly_median,gross_monthly_mean,gross_monthly_median,gross_mthly_25_percentile,gross_mthly_75_percentile,gross_monthly_mean.1,gross_monthly_median.1,...,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Key
0,97.4,96.1,3701,3200,3727,3350,2900,4000,3727,3350,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,97.1,95.7,2850,2700,2938,2700,2700,2900,2938,2700,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
2,90.9,85.7,3053,3000,3214,3000,2700,3500,3214,3000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
3,87.5,87.5,3557,3400,3615,3400,3000,4100,3615,3400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
4,95.3,95.3,3494,3500,3536,3500,3100,3816,3536,3500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5135 entries, 0 to 5134
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   employment_rate_overall      5027 non-null   object
 1   employment_rate_ft_perm      5027 non-null   object
 2   basic_monthly_mean           5027 non-null   object
 3   basic_monthly_median         5027 non-null   object
 4   gross_monthly_mean           5027 non-null   object
 5   gross_monthly_median         5027 non-null   object
 6   gross_mthly_25_percentile    5027 non-null   object
 7   gross_mthly_75_percentile    5027 non-null   object
 8   gross_monthly_mean.1         5027 non-null   object
 9   gross_monthly_median.1       5027 non-null   object
 10  gross_mthly_25_percentile.1  5027 non-null   object
 11  gross_mthly_75_percentile.1  5027 non-null   object
 12  Unnamed: 12                  0 non-null      float64
 13  Unnamed: 13                  0 non-null      float64
 14  Unnamed: 14                  0 non-null      float64
 15  Unnamed: 15                  0 non-null      float64
 16  Unnamed: 16                  0 non-null      float64
 17  Unnamed: 17                  0 non-null      float64
 18  Unnamed: 18                  0 non-null      float64
 19  Unnamed: 19                  0 non-null      float64
 20  Unnamed: 20                  0 non-null      float64
 21  Unnamed: 21                  0 non-null      float64
 22  Unnamed: 22                  0 non-null      float64
 23  Unnamed: 23                  0 non-null      float64
 24  Unnamed: 24                  0 non-null      float64
 25  Unnamed: 25                  0 non-null      float64
 26  Unnamed: 26                  0 non-null      float64
 27  Unnamed: 27                  0 non-null      float64
 28  Unnamed: 28                  0 non-null      float64
 29  Unnamed: 29                  0 non-null      float64
 30  Unnamed: 30                  0 non-null      float64
 31  Unnamed: 31                  0 non-null      float64
 32  Unnamed: 32                  0 non-null      float64
 33  Unnamed: 33                  0 non-null      float64
 34  Unnamed: 34                  0 non-null      float64
 35  Unnamed: 35                  0 non-null      float64
 36  Unnamed: 36                  0 non-null      float64
 37  Unnamed: 37                  0 non-null      float64
 38  Unnamed: 38                  0 non-null      float64
 39  Unnamed: 39                  0 non-null      float64
 40  Unnamed: 40                  0 non-null      float64
 41  Unnamed: 41                  0 non-null      float64
 42  Unnamed: 42                  0 non-null      float64
 43  Unnamed: 43                  0 non-null      float64
 44  Unnamed: 44                  0 non-null      float64
 45  Unnamed: 45                  0 non-null      float64
 46  Unnamed: 46                  0 non-null      float64
 47  Key                          5135 non-null   int64
dtypes: float64(35), int64(1), object(12)
memory usage: 1.9+ MB
None

In [6]:
df2 = df2.drop(columns=df2.columns[df2.columns.str.contains('Unnamed')])
df = df2.merge(df1, on='Key')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5135 entries, 0 to 5134
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   employment_rate_overall      5027 non-null   object
 1   employment_rate_ft_perm      5027 non-null   object
 2   basic_monthly_mean           5027 non-null   object
 3   basic_monthly_median         5027 non-null   object
 4   gross_monthly_mean           5027 non-null   object
 5   gross_monthly_median         5027 non-null   object
 6   gross_mthly_25_percentile    5027 non-null   object
 7   gross_mthly_75_percentile    5027 non-null   object
 8   gross_monthly_mean.1         5027 non-null   object
 9   gross_monthly_median.1       5027 non-null   object
 10  gross_mthly_25_percentile.1  5027 non-null   object
 11  gross_mthly_75_percentile.1  5027 non-null   object
 12  Key                          5135 non-null   int64
 13  year                         5135 non-null   object
 14  university                   5135 non-null   object
 15  school                       5135 non-null   object
 16  degree                       5135 non-null   object
dtypes: int64(1), object(16)
memory usage: 682.1+ KB

In [9]:
df.dropna(inplace=True)
df = df[df['basic_monthly_mean']!='na']
df.info()
df.head(5)

<class 'pandas.core.frame.DataFrame'>
Index: 4657 entries, 0 to 5134
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   employment_rate_overall      4657 non-null   object
 1   employment_rate_ft_perm      4657 non-null   object
 2   basic_monthly_mean           4657 non-null   object
 3   basic_monthly_median         4657 non-null   object
 4   gross_monthly_mean           4657 non-null   object
 5   gross_monthly_median         4657 non-null   object
 6   gross_mthly_25_percentile    4657 non-null   object
 7   gross_mthly_75_percentile    4657 non-null   object
 8   gross_monthly_mean.1         4657 non-null   object
 9   gross_monthly_median.1       4657 non-null   object
 10  gross_mthly_25_percentile.1  4657 non-null   object
 11  gross_mthly_75_percentile.1  4657 non-null   object
 12  Key                          4657 non-null   int64
 13  year                         4657 non-null   object
 14  university                   4657 non-null   object
 15  school                       4657 non-null   object
 16  degree                       4657 non-null   object
dtypes: int64(1), object(16)
memory usage: 654.9+ KB

C:\Users\MZafr\AppData\Local\Temp\ipykernel_26016\1088295248.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

,employment_rate_overall,employment_rate_ft_perm,basic_monthly_mean,basic_monthly_median,gross_monthly_mean,gross_monthly_median,gross_mthly_25_percentile,gross_mthly_75_percentile,gross_monthly_mean.1,gross_monthly_median.1,gross_mthly_25_percentile.1,gross_mthly_75_percentile.1,Key,year,university,school,degree
0,97.4,96.1,3701,3200,3727,3350,2900,4000,3727,3350,2900,4000,1,2013,Nanyang Technological University,College of Business (Nanyang Business School),Accountancy and Business
1,97.1,95.7,2850,2700,2938,2700,2700,2900,2938,2700,2700,2900,2,2013,Nanyang Technological University,College of Business (Nanyang Business School),Accountancy (3-yr direct Honours Programme)
2,90.9,85.7,3053,3000,3214,3000,2700,3500,3214,3000,2700,3500,3,2013,Nanyang Technological University,College of Business (Nanyang Business School),Business (3-yr direct Honours Programme)
3,87.5,87.5,3557,3400,3615,3400,3000,4100,3615,3400,3000,4100,4,2013,Nanyang Technological University,College of Business (Nanyang Business School),Business and Computing
4,95.3,95.3,3494,3500,3536,3500,3100,3816,3536,3500,3100,3816,5,2013,Nanyang Technological University,College of Engineering,Aerospace Engineering

In [10]:
df.sort_values(by='basic_monthly_mean')
df

,employment_rate_overall,employment_rate_ft_perm,basic_monthly_mean,basic_monthly_median,gross_monthly_mean,gross_monthly_median,gross_mthly_25_percentile,gross_mthly_75_percentile,gross_monthly_mean.1,gross_monthly_median.1,gross_mthly_25_percentile.1,gross_mthly_75_percentile.1,Key,year,university,school,degree
0,97.4,96.1,3701,3200,3727,3350,2900,4000,3727,3350,2900,4000,1,2013,Nanyang Technological University,College of Business (Nanyang Business School),Accountancy and Business
1,97.1,95.7,2850,2700,2938,2700,2700,2900,2938,2700,2700,2900,2,2013,Nanyang Technological University,College of Business (Nanyang Business School),Accountancy (3-yr direct Honours Programme)
2,90.9,85.7,3053,3000,3214,3000,2700,3500,3214,3000,2700,3500,3,2013,Nanyang Technological University,College of Business (Nanyang Business School),Business (3-yr direct Honours Programme)
3,87.5,87.5,3557,3400,3615,3400,3000,4100,3615,3400,3000,4100,4,2013,Nanyang Technological University,College of Business (Nanyang Business School),Business and Computing
4,95.3,95.3,3494,3500,3536,3500,3100,3816,3536,3500,3100,3816,5,2013,Nanyang Technological University,College of Engineering,Aerospace Engineering
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5130,100,90.9,378.6,372.5,386.2,380,350,400,386.2,380,350,400,5131,2012,Singapore Management University,School of Information Systems (4-year programm...,Information Systems Management (4-years progra...
5131,86.5,79.8,312.2,300,315,300,260,332,315,300,260,332,5132,2012,Singapore Management University,School of Social Sciences (4-year programme) *,Social Sciences (4-years programme)
5132,87.5,83.3,325.1,320,326.7,320,280,378.1,326.7,320,280,378.1,5133,2012,Singapore Management University,School of Social Sciences (4-year programme) *,Social Sciences (4-years programme) Cum Laude ...
5133,100,100,502.3,480,524.6,500,450,600,524.6,500,450,600,5134,2012,Singapore Management University,School of Law (4-year programme) *,Law (4-years programme) #
5134,100,100,532.9,500,561.7,554.7,475,640,561.7,554.7,475,640,5135,2012,Singapore Management University,School of Law (4-year programme) *,Law (4-years programme) Cum Laude and above #

In [ ]:
display(df3.head())
print(df3.info)

In [ ]:
print(f'{df3['employed'].unique()[:20]}\n')  # Check for any weird values like '-' or 'na'

print(df3[df3['employed'] == '-'])

In [ ]:
# Convert '-' to NaN and make the column numeric
df3['employed'] = pd.to_numeric(df3['employed'], errors='coerce')

# Verify it worked
print(df3.info())

In [ ]:
display(df4.head())
print(df4.info())

In [ ]:
# Rename the first two columns
df4 = df4.rename(columns={
    'Unnamed: 0': 'Category',
    'Unnamed: 1': 'Occupation'
})

# Check the result
print(df4[['Category','Occupation',2013]].tail(20))

In [ ]:
# See all unique values in the Category column to understand the structure
print(f'{df4['Category'].unique()}\n')
print(df4['Occupation'].unique())

In [ ]:
# 1. Remove the footer rows (source notes, etc.)
df4 = df4[df4['Occupation'].notna()]  # Keep only rows with actual occupation data

# 2. Forward fill the Category column (fills NaN with previous value)
df4['Category'] = df4['Category'].ffill() 

# 3. Check the result
df4.head(15)